apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  containers:
  - name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "2Gi"
        cpu: "2"
    ports:
    - containerPort: 9200
    - containerPort: 9300
    env:
    - name: discovery.type
      value: single-node
    volumeMounts:
    - name: elasticsearch-data
      mountPath: /usr/share/elasticsearch/data
  volumes:
  - name: elasticsearch-data
    emptyDir: {}  # Temporary storage, data is lost on pod restart

