apiVersion: v1
kind: Pod
metadata:
  name: jupyterhub
  labels:
    app: jupyterhub
spec:
  containers:
  - name: jupyterhub
    image: phuongbac/jupyterhub-custom:latest
    ports:
    - containerPort: 8000

