apiVersion: v1
kind: Pod
metadata:
  name: kafka-zookeeper
  labels:
    app: kafka-zookeeper
spec:
  containers:
  - name: zookeeper
    image: bitnami/zookeeper:latest
    env:
    - name: ALLOW_ANONYMOUS_LOGIN
      value: "yes"
    ports:
    - containerPort: 2181
      name: zk-client
  - name: kafka
    image: bitnami/kafka:latest
    env:
    - name: KAFKA_CFG_LISTENERS
      value: "PLAINTEXT://0.0.0.0:9092"
    - name: KAFKA_CFG_ZOOKEEPER_CONNECT
      value: "localhost:2181"
    - name: KAFKA_CFG_ADVERTISED_LISTENERS
      value: "PLAINTEXT://kafka-service:9092"
    - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
      value: "true"
    - name: KAFKA_CFG_MESSAGE_MAX_BYTES
      value: "209715200"  # Set to 200 MB (adjust as needed)
    - name: KAFKA_CFG_REPLICA_FETCH_MAX_BYTES
      value: "209715200"  # Must match or exceed the above value
    - name: KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES
      value: "209715200" # Set to match the above
    - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
      value: "PLAINTEXT:PLAINTEXT"

    ports:
    - containerPort: 9092
      name: kafka
    volumeMounts:
    - name: kafka-data
      mountPath: /bitnami/kafka
  volumes:
  - name: kafka-data
    emptyDir: {}

