apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  type: NodePort  # Change service type to NodePort
  ports:
  - name: http
    port: 9200
    targetPort: 9200
    nodePort: 32000  # Custom NodePort for HTTP (range: 30000-32767)
  - name: transport
    port: 9300
    targetPort: 9300
    nodePort: 32001  # Custom NodePort for transport
  selector:
    app: elasticsearch

