apiVersion: v1
kind: Service
metadata:
  name: jupyterhub
spec:
  type: NodePort  # Change service type to NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 32004  # Optional: Specify a NodePort in the range 30000–32767
  selector:
    app: jupyterhub

