apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: default
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672           # Target port in the container
      targetPort: 5672     # Container's AMQP port
      nodePort: 30072      # NodePort for external access
    - name: management
      protocol: TCP
      port: 15672          # Target port in the container
      targetPort: 15672    # Container's Management UI port
      nodePort: 30080      # NodePort for external access

