apiVersion: apps/v1
kind: Deployment
metadata:
  name: video
  labels:
    app: video
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video
  template:
    metadata:
      labels:
        app: video
    spec:
      containers:
      - name: vlc
        image: tuongvx/vlc-app:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        args: ["frozen.mp4", "--loop", "--sout", "#transcode{scodec=none}:http{mux=ffmpeg{mux=flv},dst=:8080/}"]

