apiVersion: v1
kind: Service
metadata:
  name: video-service
  labels:
    app: video
spec:
  type: NodePort
  selector:
    app: video
  ports:
  - port: 8080             # Port the service exposes
    targetPort: 8080       # Port on the container
    protocol: TCP
    nodePort: 30080        # NodePort to use (optional, Kubernetes assigns one if not specified)

